version: '3.0'

services:
  mariadb-galera-first:
    image: 'docker.io/bitnami/mariadb-galera:10.8'
    ports:
      - '3307:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - ./data/db:/bitnami/mariadb
    environment:
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackuppassword
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=P4SSW0RD123
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  mariadb-galera-second:
    image: 'docker.io/bitnami/mariadb-galera:10.8'
    ports:
      - '3308:3306'
      - '4445:4444'
      - '4569:4567'
      - '4570:4568'
    volumes:
      - ./data/db2:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-first:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackuppassword
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=P4SSW0RD123
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-first   